version: '3'

services:
  jzbot-back:
    # 使用本地构建的镜像
    build:
        context: .
        dockerfile: Dockerfile
    # 容器名称
    container_name: jzbot-back
    # 端口映射
    ports:
      - "8003:80"
    # 环境变量 - 设置时区
    environment:
      - TZ=Asia/Shanghai
    # 目录映射
    volumes:
      # 映射日志目录
      - ./Logs:/app/Logs
      - ./keys:/app/keys
      - ./appsettings.json:/app/appsettings.json
      - ./Sqlite.db:/app/Sqlite.db
      # 映射时区文件（可选）
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # 容器重启策略
    restart: unless-stopped
